# Generated by Django 5.2.7 on 2025-10-20 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da ONG')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('area_atuacao', models.CharField(max_length=150, verbose_name='Área de Atuação')),
                ('contato', models.CharField(help_text='E-mail ou telefone principal', max_length=100)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='ongs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='documentos_ongs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastro.ong')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário da Avaliação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastro.ong')),
            ],
        ),
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('ativo', models.BooleanField(default=True)),
                ('avaliacao_origem', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.avaliacao')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selos', to='cadastro.ong')),
            ],
        ),
    ]
