# Generated by Django 5.2.8 on 2025-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selo',
            name='avaliacao_origem',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='selo',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='area_atuacao',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='ong',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='motivacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='representante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Selo',
        ),
    ]
