# Generated by Django 5.2.8 on 2025-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_selo_avaliacao_origem_remove_documento_ong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
    ]
