# Generated by Django 5.2.8 on 2025-11-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_instituicao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instituicao',
            new_name='Parceiro',
        ),
    ]
